### PR TITLE
CMake scripts for the entire repo

### PR DESCRIPTION
**Pull request by edrthomas**
This PR provides CMake scripts to build the reference software library and tools.

It does not yet remove the legacy scripts, i.e. makefiles, vs studio and xcode. 

This will be done at a later stage when compilation will be validated on these platforms.

### CODE REVIEW

**Comment by edrthomas** [comment]
@cconcolato, before merging we should check that compiling still works on different platforms. The travis builds validates at least for Linux. I will check on Windows on my side. Can you please check on Mac OS X?

**Comment by edrthomas** [comment]
I fixed few linking issues on windows. It compiles now on my test machine (Windows 10 64 bits).

**Comment by ahmedhmz** [comment]
@edrthomas, I also managed to compile on Windows 10 64-bit for Visual Studio 2015. One small suggestion so that all output files are not generated in the src directory in the respective project directory for audio_example and drc_in_isom is to avoid having a CMakeLists.txt file in the src directories and moving the contents of these files to the CMakeLists.txt file in the project directory. Examples attached. I haven't tested on Linux though.

[CMakeLists (audio_example).txt](https://github.com/MPEGGroup/isobmff/files/3035474/CMakeLists.audio_example.txt)

[CMakeLists (drc_in_isom).txt](https://github.com/MPEGGroup/isobmff/files/3035468/CMakeLists.drc_in_isom.txt)

**Comment by edrthomas** [comment]
Ok so I am hearing successful compilation on Mac OS, Windows and Linux on at least common versions. I will proceed with the merge then.

@ahmedhmz , you are right, I'll make the change you suggest to be consistent with the rest of the other cmakefiles.

**Pull request merged**
