### PR TITLE
CMakeLists.txt for libisomediafile

### PR DESCRIPTION
**Pull request by dfisc**
Hi isobmff maintainers, 
In the past I had problems building libisomediafile on Windows with recent versions of Visual Studio. I couldn't find a cmake list, so I wrote this one.
Tested the build on Linux, Windows and Mac. Currently, I use it with the MPEG-4 audio reference software. 

Best, Daniel

### CODE REVIEW

**Comment by edrthomas** [comment]
Hi Daniel,

Thanks for raising the problem of compiling on recent version of Windows. I do like the proposal to use cmake to keep the project cross-platform more easily.

However, I am afraid that having the cmake list and at the same time the compilation files for each platform (e.g. makefile for linux)  is confusing. So I would not support merging this PR.

I would rather suggest we create a new issue to migrate to cmake all the build processes, not only libisomedialfile.

Opinion?

**Comment by ahmedhmz** [comment]
Thanks, Daniel. Indeed, I support migrating to CMake for cross-platform building. That said, I agree with @edrthomas that we should do so for all projects and completely remove platform-specific build scripts/files. Otherwise, it will be confusing for someone cloning the repository. However, I believe this is a good start. And the contribution is much appreciated.

**Comment by edrthomas** [comment]
As reported in the File Format session at MPEG 126, I am working on making the entire repo cmake based. This pull request is valuable and I am using it as a starting point.

**Comment by edrthomas** [comment]
Used as input for #16.

**Pull request closed without merging**
